project:
  type: book
  output-dir: ../docs/en

lang: en-GB

bibliography: ../referencias.bib

book:
  title: "Web Applications and Services"
  subtitle: "Course Textbook"
  author:
    - name: "João Pavão"
      affiliation: "University of Trás-os-Montes e Alto Douro"
  date: last-modified

  chapters:
    - index.qmd
    - capitulos/cap01.qmd
    - capitulos/cap02.qmd
    - capitulos/cap03.qmd
    - capitulos/cap04.qmd
    - capitulos/cap05.qmd
    - capitulos/cap06.qmd
    - capitulos/cap07.qmd
    - capitulos/cap08.qmd
    - references.qmd

  appendices:
    - capitulos/apendiceA.qmd
    - capitulos/apendiceB.qmd
    - capitulos/apendiceC.qmd
    - capitulos/apendiceD1.qmd
    - capitulos/apendiceD2.qmd
    - capitulos/apendiceD3.qmd
    - capitulos/apendiceD4.qmd
    - capitulos/apendiceD5.qmd
    - capitulos/apendiceD6.qmd

  sidebar:
    search: true
    tools:
      - icon: translate
        href: /../index.html
        text: "Versão portuguesa"

  page-footer:
    left: "Web Applications and Services — MEEC · UTAD"

format:
  html:
    theme:
      light: litera
      dark: darkly
    css: /assets/css/custom.css
    toc: true
    toc-depth: 3
    smooth-scroll: true
    number-sections: true
    number-depth: 3
    highlight-style: github
    code-fold: false
    code-tools: false
    code-line-numbers: true
    fig-align: center

execute:
  echo: true
  warning: false
  message: false
