<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-PT" xml:lang="pt-PT"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="João Pavão">

<title>3&nbsp; O Protocolo HTTP – Aplicações e Serviços Web</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../capitulos/cap04.html" rel="next">
<link href="../capitulos/cap02.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de84f8d6bb715db06a919283c2d1e787.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-9a023c9ade86a60361e96e3e3f11bc54.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-61bc4ac84974e0785b3107ee93e74bfb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-bc9f1d3aef906c45e091843ae87821a0.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../assets/css/custom.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../capitulos/cap03.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">O Protocolo HTTP</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Aplicações e Serviços Web</a> 
        <div class="sidebar-tools-main">
    <a href="../en/" title="English version" class="quarto-navigation-tool px-1" aria-label="English version"><i class="bi bi-translate"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo escuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefácio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Arquitetura de Aplicações Web</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">HTML, CSS e Bootstrap</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap03.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">O Protocolo HTTP</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Java EE e Fundamentos de Servlets</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelo Stateful: Sessões e JSP</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Segurança e Filtros</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Web Services REST e Arquitetura Stateless (Parte 1)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Web Services REST (Parte 2) e o Cliente em JavaScript</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Apêndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/apendiceA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Código Completo: Páginas Estáticas “World Capitals”</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/apendiceB.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Assinatura de Tokens JWT</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/apendiceC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Configuração do Ambiente de Desenvolvimento</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/apendiceD1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">LAB1: Primeiro Endpoint e DAO Simulado</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/apendiceD2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">LAB2: Login e Sessão</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/apendiceD3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">LAB3: AuthenticationFilter e Logout</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/apendiceD4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">LAB4: JDBC e CRUD Completo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/apendiceD5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">H</span>&nbsp; <span class="chapter-title">LAB5 (Opcional): Autenticação Sem Estado com JWT</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/apendiceD6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">I</span>&nbsp; <span class="chapter-title">LAB6: O Front-Office em JavaScript</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#sec-03-middleware-intro" id="toc-sec-03-middleware-intro" class="nav-link active" data-scroll-target="#sec-03-middleware-intro"><span class="header-section-number">3.1</span> O Middleware que Liga Frontend e Backend</a></li>
  <li><a href="#sec-03-cliente-servidor" id="toc-sec-03-cliente-servidor" class="nav-link" data-scroll-target="#sec-03-cliente-servidor"><span class="header-section-number">3.2</span> O Modelo Cliente-Servidor</a></li>
  <li><a href="#sec-03-modelo-tcpip" id="toc-sec-03-modelo-tcpip" class="nav-link" data-scroll-target="#sec-03-modelo-tcpip"><span class="header-section-number">3.3</span> O Modelo TCP/IP</a>
  <ul class="collapse">
  <li><a href="#encapsulamento" id="toc-encapsulamento" class="nav-link" data-scroll-target="#encapsulamento"><span class="header-section-number">3.3.1</span> Encapsulamento</a></li>
  </ul></li>
  <li><a href="#sec-03-tcp-portas" id="toc-sec-03-tcp-portas" class="nav-link" data-scroll-target="#sec-03-tcp-portas"><span class="header-section-number">3.4</span> A Camada de Transporte: o TCP e as Portas</a>
  <ul class="collapse">
  <li><a href="#as-portas" id="toc-as-portas" class="nav-link" data-scroll-target="#as-portas"><span class="header-section-number">3.4.1</span> As Portas</a></li>
  <li><a href="#o-tcp" id="toc-o-tcp" class="nav-link" data-scroll-target="#o-tcp"><span class="header-section-number">3.4.2</span> O TCP</a></li>
  </ul></li>
  <li><a href="#sec-03-ip-enderecos" id="toc-sec-03-ip-enderecos" class="nav-link" data-scroll-target="#sec-03-ip-enderecos"><span class="header-section-number">3.5</span> A Camada Internet: o IP e os Endereços</a>
  <ul class="collapse">
  <li><a href="#os-endereços-ip" id="toc-os-endereços-ip" class="nav-link" data-scroll-target="#os-endereços-ip"><span class="header-section-number">3.5.1</span> Os Endereços IP</a></li>
  <li><a href="#o-encaminhamento" id="toc-o-encaminhamento" class="nav-link" data-scroll-target="#o-encaminhamento"><span class="header-section-number">3.5.2</span> O Encaminhamento</a></li>
  <li><a href="#o-dns-de-nomes-a-endereços" id="toc-o-dns-de-nomes-a-endereços" class="nav-link" data-scroll-target="#o-dns-de-nomes-a-endereços"><span class="header-section-number">3.5.3</span> O DNS: de Nomes a Endereços</a></li>
  </ul></li>
  <li><a href="#sec-03-url-ligacao" id="toc-sec-03-url-ligacao" class="nav-link" data-scroll-target="#sec-03-url-ligacao"><span class="header-section-number">3.6</span> Do <em>URL</em> à Ligação</a></li>
  <li><a href="#sec-03-o-http" id="toc-sec-03-o-http" class="nav-link" data-scroll-target="#sec-03-o-http"><span class="header-section-number">3.7</span> O HTTP</a>
  <ul class="collapse">
  <li><a href="#métodos" id="toc-métodos" class="nav-link" data-scroll-target="#métodos"><span class="header-section-number">3.7.1</span> Métodos</a></li>
  <li><a href="#sec-03-formato-mensagem" id="toc-sec-03-formato-mensagem" class="nav-link" data-scroll-target="#sec-03-formato-mensagem"><span class="header-section-number">3.7.2</span> Formato de uma Mensagem</a></li>
  <li><a href="#sec-03-codigos-estado" id="toc-sec-03-codigos-estado" class="nav-link" data-scroll-target="#sec-03-codigos-estado"><span class="header-section-number">3.7.3</span> Códigos de Estado</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">O Protocolo HTTP</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>João Pavão </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">26 de agosto de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="sec-03-middleware-intro" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-03-middleware-intro"><span class="header-section-number">3.1</span> O Middleware que Liga Frontend e Backend</h2>
<p>O <a href="../capitulos/cap01.html">Capítulo 1</a> identificou três componentes em qualquer aplicação Web: <em>Frontend</em>, <em>Middleware</em> e <em>Backend</em>. O <a href="../capitulos/cap02.html">Capítulo 2</a> dedicou-se à primeira, um conjunto de páginas HTML com formulários, entre eles o de consulta de capital (<code>capital.html</code>) e o de autenticação (<code>login.html</code>). Esses formulários, por si só, não fazem nada: precisam de um protocolo que leve os dados que o utilizador preenche até um servidor, e que traga de volta uma resposta. Esse protocolo, o <em>Middleware</em> usado nas aplicações <em>web</em>, é o HTTP (<em>HyperText Transfer Protocol</em>).</p>
<p>O HTTP, no entanto, não trabalha sozinho. Para que um pedido saia do <em>browser</em> e chegue a um servidor, possivelmente do outro lado do mundo, o HTTP apoia-se em dois outros protocolos: o TCP, que entrega os dados à aplicação certa, e o IP, que os faz chegar à máquina certa. Este capítulo percorre esse caminho por ordem: parte do modelo cliente-servidor, desce às camadas de transporte e de rede para mostrar onde entram as portas e os endereços IP, e só depois detalha o funcionamento do HTTP.</p>
</section>
<section id="sec-03-cliente-servidor" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="sec-03-cliente-servidor"><span class="header-section-number">3.2</span> O Modelo Cliente-Servidor</h2>
<p>Toda a comunicação na <em>web</em> assenta no modelo cliente-servidor. Neste modelo há dois papéis bem distintos:</p>
<dl>
<dt>Servidor</dt>
<dd>
Um programa que está permanentemente à escuta, à espera de pedidos. Não toma a iniciativa de contactar ninguém: limita-se a responder a quem o contacta. Um mesmo servidor atende, em simultâneo, pedidos de muitos clientes diferentes. Nesta UC, o servidor é o Apache Tomcat.
</dd>
<dt>Cliente</dt>
<dd>
Um programa que toma a iniciativa da comunicação: envia um pedido ao servidor e aguarda a resposta. Na <em>web</em>, o cliente é tipicamente um <em>browser</em> (Chrome, Firefox, Safari), mas pode ser qualquer programa capaz de enviar pedidos, como o <code>curl</code> na linha de comandos ou uma aplicação móvel.
</dd>
</dl>
<div id="fig-03-cliente-servidor" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-03-cliente-servidor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/images/capitulos/cap01/Modelo_cliente_servidor.png" class="img-fluid figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-03-cliente-servidor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.1: O cliente (por exemplo, um browser) envia um pedido HTTP; o servidor processa-o e devolve uma resposta. A troca repete-se a cada interação, sem que o servidor guarde, por si só, memória da anterior.
</figcaption>
</figure>
</div>
<p>A interação é sempre a mesma: o cliente envia um pedido (<em>request</em>), o servidor processa-o e devolve uma resposta (<em>response</em>). Este par pedido-resposta é a unidade básica de toda a comunicação na <em>web</em>: carregar uma página, submeter um formulário ou obter uma imagem são, cada um, uma ou mais destas trocas.</p>
<p>Para que esta troca aconteça, o cliente precisa de responder a duas perguntas antes de enviar o que quer que seja:</p>
<ol type="1">
<li><strong>Em que máquina</strong> está o servidor? A resposta é um <strong>endereço IP</strong>, tratado pela camada Internet.</li>
<li><strong>Que programa</strong>, dentro dessa máquina, deve receber o pedido? Uma mesma máquina pode ter vários servidores a correr ao mesmo tempo (um servidor <em>web</em>, um servidor de base de dados, um servidor de correio). A resposta é um <strong>número de porta</strong>, tratado pela camada de Transporte.</li>
</ol>
<p>Só depois de resolvidas estas duas questões entra o HTTP, que define <strong>o que</strong> se diz: o formato do pedido e da resposta. As secções seguintes explicam como é que as três peças se organizam.</p>
</section>
<section id="sec-03-modelo-tcpip" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="sec-03-modelo-tcpip"><span class="header-section-number">3.3</span> O Modelo TCP/IP</h2>
<p>As comunicações em rede organizam-se em camadas. Cada camada presta um serviço à camada imediatamente acima e usa os serviços da camada imediatamente abaixo, sem precisar de saber como é que essas outras camadas funcionam por dentro. O modelo TCP/IP, usado na Internet, organiza a pilha de comunicações em quatro camadas:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Camada</th>
<th>Responsabilidade</th>
<th>Endereçamento</th>
<th>Exemplos de protocolos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aplicação</td>
<td>O formato dos dados trocados entre aplicações</td>
<td><em>URL</em></td>
<td>HTTP, FTP, SMTP, DNS</td>
</tr>
<tr class="even">
<td>Transporte</td>
<td>Entrega dos dados ao processo certo, de forma fiável (TCP) ou não (UDP)</td>
<td>Porta</td>
<td>TCP, UDP</td>
</tr>
<tr class="odd">
<td>Internet</td>
<td>Encaminhamento dos dados entre redes, até à máquina certa</td>
<td>Endereço IP</td>
<td>IP</td>
</tr>
<tr class="even">
<td>Acesso à Rede</td>
<td>Transmissão física dos dados no meio local</td>
<td>Endereço MAC</td>
<td>Ethernet, Wi-Fi</td>
</tr>
</tbody>
</table>
<div id="fig-03-modelo-tcpip" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-03-modelo-tcpip-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/images/capitulos/cap03/Modelo_TCP_IP.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-03-modelo-tcpip-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.2: O modelo TCP/IP em quatro camadas. O HTTP vive na camada de Aplicação, e assenta sobre o TCP (camada de Transporte) para garantir que os dados chegam de forma fiável e pela ordem correta.
</figcaption>
</figure>
</div>
<section id="encapsulamento" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="encapsulamento"><span class="header-section-number">3.3.1</span> Encapsulamento</h3>
<p>Quando o <em>browser</em> envia um pedido, os dados descem a pilha, da camada de Aplicação até à camada de Acesso à Rede. Em cada camada é acrescentado um cabeçalho próprio, com a informação de que essa camada precisa. A este processo chama-se encapsulamento (<a href="#fig-03-encapsulamento" class="quarto-xref">Figura&nbsp;<span>3.3</span></a>):</p>
<ol type="1">
<li><strong>Aplicação:</strong> o <em>browser</em> constrói a mensagem HTTP (por exemplo, <code>GET /capital?countrycode=PT</code>). Estes dados, do ponto de vista das camadas inferiores, são apenas a carga útil (<em>payload</em>).</li>
<li><strong>Transporte:</strong> o TCP acrescenta um cabeçalho cuja informação mais importante são as <strong>portas de origem e de destino</strong>. O resultado chama-se segmento TCP.</li>
<li><strong>Internet:</strong> o IP acrescenta um cabeçalho cuja informação mais importante são os <strong>endereços IP de origem e de destino</strong>. O resultado chama-se pacote IP.</li>
<li><strong>Acesso à Rede:</strong> a placa de rede acrescenta um cabeçalho com os endereços físicos (MAC) e, no fim, um código de verificação (FCS, <em>Frame Check Sequence</em>) que permite ao recetor detetar se a trama foi corrompida pelo caminho. O resultado chama-se trama (<em>frame</em>), que é depois convertida em sinais elétricos, óticos ou rádio.</li>
</ol>
<div id="fig-03-encapsulamento" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-03-encapsulamento-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/images/capitulos/cap03/Encapsulamento.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-03-encapsulamento-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.3: O encapsulamento de um pedido HTTP. Cada camada recebe da camada de cima uma unidade de dados que trata como carga útil, sem a ler, e acrescenta-lhe o seu próprio cabeçalho: as portas no segmento TCP, os endereços IP no pacote IP e os endereços MAC na trama Ethernet.
</figcaption>
</figure>
</div>
<p>Na receção, o processo inverte-se: cada camada verifica o cabeçalho que lhe diz respeito, retira-o e entrega o resto à camada de cima. A camada Internet confirma que o endereço IP de destino é o da máquina; a camada de Transporte verifica se há alguma aplicação registada na porta de destino e, em caso afirmativo, entrega-lhe os dados; a camada de Aplicação, por fim, recebe a mensagem HTTP tal como o <em>browser</em> a escreveu.</p>
<p>O HTTP é, portanto, um protocolo da camada de Aplicação: não se preocupa em saber como é que os dados chegam ao destino, apenas define o formato do pedido e da resposta. Essa entrega fica a cargo das camadas inferiores, das quais as duas mais relevantes para o desenvolvimento <em>web</em> são descritas a seguir.</p>
</section>
</section>
<section id="sec-03-tcp-portas" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="sec-03-tcp-portas"><span class="header-section-number">3.4</span> A Camada de Transporte: o TCP e as Portas</h2>
<section id="as-portas" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="as-portas"><span class="header-section-number">3.4.1</span> As Portas</h3>
<p>Um endereço IP identifica uma máquina, mas numa máquina correm muitos programas ao mesmo tempo. A porta é o número que identifica, dentro de uma máquina, o programa a que os dados se destinam. Quando um servidor arranca, regista-se numa porta e fica à escuta: todos os segmentos TCP que chegam com essa porta de destino são-lhe entregues.</p>
<p>As portas são números inteiros entre 0 e 65535, divididos em três gamas:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Gama</th>
<th>Designação</th>
<th>Utilização</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0 a 1023</td>
<td>Portas bem conhecidas (<em>well-known ports</em>)</td>
<td>Reservadas a serviços normalizados</td>
</tr>
<tr class="even">
<td>1024 a 49151</td>
<td>Portas registadas (<em>registered ports</em>)</td>
<td>Atribuídas a aplicações específicas</td>
</tr>
<tr class="odd">
<td>49152 a 65535</td>
<td>Portas dinâmicas (<em>ephemeral ports</em>)</td>
<td>Atribuídas temporariamente aos clientes</td>
</tr>
</tbody>
</table>
<p>Algumas portas surgem com particular frequência:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Porta</th>
<th>Serviço</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>21</td>
<td>FTP (transferência de ficheiros)</td>
</tr>
<tr class="even">
<td>22</td>
<td>SSH (acesso remoto seguro)</td>
</tr>
<tr class="odd">
<td>25</td>
<td>SMTP (envio de correio eletrónico)</td>
</tr>
<tr class="even">
<td>53</td>
<td>DNS (resolução de nomes)</td>
</tr>
<tr class="odd">
<td>80</td>
<td>HTTP</td>
</tr>
<tr class="even">
<td>443</td>
<td>HTTPS (HTTP cifrado)</td>
</tr>
<tr class="odd">
<td>3306</td>
<td>MySQL / MariaDB</td>
</tr>
<tr class="even">
<td>8080</td>
<td>HTTP alternativo (porta por omissão do Apache Tomcat)</td>
</tr>
</tbody>
</table>
<p>Quando a porta de destino é a bem conhecida do protocolo, não é preciso escrevê-la no <em>URL</em>: <code>http://www.utad.pt</code> e <code>http://www.utad.pt:80</code> são exatamente o mesmo endereço, porque o <em>browser</em> assume a porta 80 para <code>http</code> e a porta 443 para <code>https</code>. Já o Tomcat, que por omissão escuta na porta 8080, obriga a indicá-la explicitamente, e é por isso que todos os endereços usados nesta UC têm a forma <code>http://localhost:8080/...</code>.</p>
<p>O cliente também usa uma porta: a porta de origem. Essa não é escolhida pelo utilizador, é atribuída automaticamente pelo sistema operativo, a partir da gama dinâmica, no momento em que a ligação é aberta. É para essa porta que o servidor envia a resposta. Por isso um <em>browser</em> com vários separadores abertos no mesmo <em>site</em> consegue receber as respostas de cada um sem as misturar: cada ligação tem a sua porta de origem.</p>
<p>Ao par formado por um endereço IP e uma porta chama-se <strong><em>socket</em></strong>. Uma ligação TCP fica completamente identificada por dois <em>sockets</em>: o do cliente (por exemplo, <code>192.168.1.20:51734</code>) e o do servidor (por exemplo, <code>203.0.113.10:80</code>).</p>
</section>
<section id="o-tcp" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="o-tcp"><span class="header-section-number">3.4.2</span> O TCP</h3>
<p>O TCP (<em>Transmission Control Protocol</em>) é o protocolo de transporte usado pelo HTTP. A sua função é garantir que os dados chegam ao destino <strong>completos, sem erros e pela ordem em que foram enviados</strong>, apesar de a rede por baixo (o IP) não oferecer nenhuma destas garantias. Para isso, o TCP:</p>
<ul>
<li><strong>Estabelece uma ligação</strong> antes de enviar dados: cliente e servidor trocam três mensagens de sincronização (o chamado <em>three-way handshake</em>) e só depois começa a transferência. É por isso que se diz que o TCP é orientado à ligação.</li>
<li><strong>Numera os segmentos:</strong> quando os dados são extensos, o TCP parte-os em vários segmentos e atribui a cada um um número de sequência. O recetor usa esses números para os reordenar e para detetar se falta algum.</li>
<li><strong>Confirma a receção:</strong> o recetor responde ao emissor com uma confirmação (<em>acknowledgement</em>) dos segmentos recebidos. Se um segmento não for confirmado dentro de um certo tempo, o emissor volta a enviá-lo.</li>
<li><strong>Controla o fluxo:</strong> o emissor ajusta a quantidade de dados que envia de uma só vez à capacidade de resposta do recetor e ao estado da rede, para não os sobrecarregar.</li>
</ul>
<p>Para quem desenvolve aplicações <em>web</em>, a consequência prática é simples: quando o servidor lê um pedido HTTP, pode contar que esse pedido está inteiro e na ordem certa. Toda a complexidade de lidar com perdas e retransmissões fica escondida dentro do TCP.</p>
<p>A alternativa ao TCP na camada de Transporte é o UDP (<em>User Datagram Protocol</em>), que também usa portas mas dispensa a ligação, a numeração e as confirmações. É mais rápido mas não garante a entrega, e é usado em situações onde perder um pacote ocasional é preferível a esperar pela sua retransmissão, como chamadas de voz, vídeo em direto ou consultas DNS.</p>
</section>
</section>
<section id="sec-03-ip-enderecos" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="sec-03-ip-enderecos"><span class="header-section-number">3.5</span> A Camada Internet: o IP e os Endereços</h2>
<section id="os-endereços-ip" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="os-endereços-ip"><span class="header-section-number">3.5.1</span> Os Endereços IP</h3>
<p>O IP (<em>Internet Protocol</em>) é responsável por fazer chegar cada pacote à máquina de destino, identificada pelo seu endereço IP. Na versão 4 do protocolo (IPv4), ainda a mais comum, um endereço IP é formado por quatro números entre 0 e 255, separados por pontos, como <code>203.0.113.10</code> ou <code>192.168.1.20</code>. Cada um destes números ocupa 8 bits, o que faz de um endereço IPv4 um número de 32 bits, com cerca de 4 300 milhões de combinações possíveis. Esse número revelou-se insuficiente para o crescimento da Internet, e deu origem ao IPv6, com endereços de 128 bits escritos em hexadecimal (por exemplo, <code>2001:db8::10</code>), que coexiste hoje com o IPv4.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Endereços usados nos exemplos
</div>
</div>
<div class="callout-body-container callout-body">
<p>Os endereços públicos que aparecem neste capítulo (<code>203.0.113.10</code>, <code>2001:db8::10</code>) e o nome <code>www.example.com</code> não pertencem a nenhuma máquina real: fazem parte de blocos reservados pelas normas da Internet exclusivamente para documentação e exemplos (RFC 5737 e RFC 3849 para os endereços, RFC 2606 para os nomes). Os endereços <code>192.168.1.20</code> e <code>127.0.0.1</code>, pelo contrário, são endereços reais, de uso privado e de <em>loopback</em>, respetivamente, e são explicados a seguir.</p>
</div>
</div>
<p>Tal como acontece com as portas, há endereços reservados para fins específicos:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Endereço ou gama</th>
<th>Utilização</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>127.0.0.1</code></td>
<td><em>Loopback</em>: a própria máquina (nome <code>localhost</code>)</td>
</tr>
<tr class="even">
<td><code>10.0.0.0</code> a <code>10.255.255.255</code></td>
<td>Endereços privados (redes internas)</td>
</tr>
<tr class="odd">
<td><code>172.16.0.0</code> a <code>172.31.255.255</code></td>
<td>Endereços privados (redes internas)</td>
</tr>
<tr class="even">
<td><code>192.168.0.0</code> a <code>192.168.255.255</code></td>
<td>Endereços privados (redes domésticas e de escritório)</td>
</tr>
</tbody>
</table>
<p>O endereço <code>127.0.0.1</code> merece destaque nesta UC. Um pedido enviado para <code>localhost</code> nunca sai da máquina: desce a pilha de comunicações e volta a subi-la no mesmo computador, onde o Tomcat o recebe. É isso que permite desenvolver e testar uma aplicação <em>web</em> completa, cliente e servidor, num único portátil e sem ligação à Internet.</p>
<p>Os endereços privados, por sua vez, só são válidos dentro de uma rede local. É por isso que o portátil de um aluno pode ter o endereço <code>192.168.1.20</code> em casa e outro endereço diferente na rede da universidade. Para comunicar com o exterior, o <em>router</em> da rede local traduz esse endereço privado num endereço público, num processo chamado NAT (<em>Network Address Translation</em>).</p>
</section>
<section id="o-encaminhamento" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="o-encaminhamento"><span class="header-section-number">3.5.2</span> O Encaminhamento</h3>
<p>O cliente e o servidor raramente estão na mesma rede. Um pacote IP enviado de casa de um aluno para o servidor da UTAD atravessa várias redes intermédias. Em cada uma delas, um equipamento chamado <em>router</em> lê o endereço IP de destino, consulta a sua tabela de encaminhamento (<em>routing table</em>) e decide para que rede vizinha deve reenviar o pacote. O pacote avança assim, salto a salto, até à rede onde está o servidor.</p>
<p>Este encaminhamento é feito pacote a pacote, e o IP não dá qualquer garantia de entrega: um pacote pode perder-se, chegar duplicado ou chegar fora de ordem em relação aos que foram enviados antes. É precisamente para compensar estas falhas que o TCP existe na camada acima.</p>
</section>
<section id="o-dns-de-nomes-a-endereços" class="level3" data-number="3.5.3">
<h3 data-number="3.5.3" class="anchored" data-anchor-id="o-dns-de-nomes-a-endereços"><span class="header-section-number">3.5.3</span> O DNS: de Nomes a Endereços</h3>
<p>Os endereços IP são práticos para as máquinas mas difíceis de memorizar para as pessoas. É por isso que no <em>browser</em> se escreve <code>www.example.com</code> e não <code>203.0.113.10</code>. A rede, porém, só conhece endereços IP: antes de poder enviar o que quer que seja, o <em>browser</em> tem de converter o nome no endereço correspondente.</p>
<p>Essa conversão é feita pelo DNS (<em>Domain Name System</em>), um sistema hierárquico de servidores distribuídos pela Internet. O <em>browser</em> pergunta ao DNS qual o endereço IP associado a um nome, e o DNS responde com o endereço que o <em>browser</em> vai depois colocar no cabeçalho IP dos pacotes. O nome <code>localhost</code> é um caso especial: é resolvido pela própria máquina, diretamente para <code>127.0.0.1</code>, sem consultar nenhum servidor DNS.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Perguntar diretamente ao DNS
</div>
</div>
<div class="callout-body-container callout-body">
<p>O comando <code>nslookup</code>, disponível em Windows, macOS e Linux, faz a mesma pergunta que o <em>browser</em> faz ao DNS e mostra a resposta. Num terminal:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1"></a><span class="ex">nslookup</span> www.utad.pt</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>A resposta indica o servidor DNS que foi consultado e, na linha <code>Address</code>, o endereço IP (ou endereços, IPv4 e IPv6) associado ao nome. Repetir o comando com outros nomes (por exemplo, <code>www.google.com</code>) mostra que um mesmo nome pode estar associado a vários endereços. Note-se que o <code>nslookup</code> consulta sempre um servidor DNS, ao contrário do <em>browser</em>, que resolve <code>localhost</code> localmente; por isso o resultado de <code>nslookup localhost</code> varia de sistema para sistema e não é um bom exemplo.</p>
</div>
</div>
</section>
</section>
<section id="sec-03-url-ligacao" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="sec-03-url-ligacao"><span class="header-section-number">3.6</span> Do <em>URL</em> à Ligação</h2>
<p>Com as três camadas apresentadas, é possível acompanhar tudo o que acontece quando o utilizador submete o formulário de consulta de capital e o <em>browser</em> tem de aceder ao endereço:</p>
<pre><code>http://localhost:8080/capital?countrycode=PT</code></pre>
<p>O <em>URL</em> contém, ele próprio, a informação de que cada camada precisa:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Parte do <em>URL</em></th>
<th>Valor</th>
<th>Camada que a usa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Protocolo</td>
<td><code>http</code></td>
<td>Aplicação: define o protocolo e a porta por omissão (80)</td>
</tr>
<tr class="even">
<td>Anfitrião (<em>host</em>)</td>
<td><code>localhost</code></td>
<td>Internet: convertido em endereço IP pelo DNS (<code>127.0.0.1</code>)</td>
</tr>
<tr class="odd">
<td>Porta</td>
<td><code>8080</code></td>
<td>Transporte: identifica o Tomcat dentro da máquina</td>
</tr>
<tr class="even">
<td>Caminho e parâmetros</td>
<td><code>/capital?countrycode=PT</code></td>
<td>Aplicação: identifica o recurso pedido ao servidor</td>
</tr>
</tbody>
</table>
<p>A partir daqui, a sequência é sempre a mesma:</p>
<ol type="1">
<li>O <em>browser</em> extrai o nome do anfitrião do <em>URL</em> e obtém o seu endereço IP (através do DNS ou, no caso de <code>localhost</code>, diretamente).</li>
<li>O <em>browser</em> abre uma ligação TCP para o <em>socket</em> do servidor, <code>127.0.0.1:8080</code>. O sistema operativo atribui ao cliente uma porta de origem da gama dinâmica.</li>
<li>O <em>browser</em> escreve a mensagem de pedido HTTP e entrega-a ao TCP, que a divide em segmentos, lhe acrescenta as portas e a passa ao IP, que lhe acrescenta os endereços.</li>
<li>Do lado do servidor, os pacotes sobem a pilha: o IP reconhece o seu endereço, o TCP reconstitui a mensagem e entrega-a ao programa registado na porta 8080, o Tomcat.</li>
<li>O Tomcat processa o pedido e escreve a resposta HTTP, que faz o percurso inverso até à porta de origem do <em>browser</em>.</li>
<li>O <em>browser</em> lê a resposta e apresenta-a ao utilizador.</li>
</ol>
<p>Os passos 1, 2 e 4 são inteiramente tratados pelo sistema operativo e pela rede; os passos 3, 5 e 6, na parte que diz respeito ao conteúdo da mensagem, são definidos pelo HTTP. É esse conteúdo, o que o cliente pede e o que o servidor responde, que o resto deste capítulo detalha.</p>
</section>
<section id="sec-03-o-http" class="level2 page-columns page-full" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="sec-03-o-http"><span class="header-section-number">3.7</span> O HTTP</h2>
<p>O <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP">HTTP</a> (<em>HyperText Transfer Protocol</em>) é um protocolo de texto, baseado no modelo pedido-resposta: o cliente envia um pedido, o servidor devolve uma resposta, e a ligação entre os dois não guarda memória de pedidos anteriores. Cada pedido é tratado de forma independente, isto é, o HTTP não tem estado (é <em>stateless</em>). Esta secção detalha os três aspetos que definem um pedido e uma resposta: os métodos, o formato geral da mensagem e os códigos de estado.</p>
<section id="métodos" class="level3" data-number="3.7.1">
<h3 data-number="3.7.1" class="anchored" data-anchor-id="métodos"><span class="header-section-number">3.7.1</span> Métodos</h3>
<p>Cada pedido do cliente ao servidor é feito no formato HTTP e indica, através de um método, a operação que se pretende realizar sobre um determinado recurso. O “recurso” no contexto das aplicações <em>web</em> pode ser uma página <code>html</code>, uma imagem, um <code>PDF</code>, ou qualquer outro suscetível de ser manipulado digitalmente:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Método</th>
<th>Semântica típica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>GET</code></td>
<td>Obter um recurso</td>
</tr>
<tr class="even">
<td><code>POST</code></td>
<td>Criar um recurso</td>
</tr>
<tr class="odd">
<td><code>PUT</code></td>
<td>Atualizar ou substituir um recurso</td>
</tr>
<tr class="even">
<td><code>DELETE</code></td>
<td>Remover um recurso</td>
</tr>
<tr class="odd">
<td><code>HEAD</code></td>
<td>Obter apenas os cabeçalhos, sem corpo</td>
</tr>
</tbody>
</table>
<p>Estes cinco métodos cobrem a generalidade das operações realizadas por uma aplicação Web; os dois primeiros (<code>GET</code> e <code>POST</code>) são, de longe, os mais usados em páginas <em>web</em>, enquanto <code>PUT</code> e <code>DELETE</code> ganham importância sobretudo nos serviços <em>web</em>.</p>
</section>
<section id="sec-03-formato-mensagem" class="level3 page-columns page-full" data-number="3.7.2">
<h3 data-number="3.7.2" class="anchored" data-anchor-id="sec-03-formato-mensagem"><span class="header-section-number">3.7.2</span> Formato de uma Mensagem</h3>
<p>Quando a aplicação no computador do cliente quer comunicar com o servidor, ativa a camada de Aplicação da pilha protocolar de comunicações, a qual formata o pedido de acordo com o protocolo HTTP. Tanto um pedido como a resposta que se lhe segue apresentam uma estrutura geral de uma mensagem semelhante:</p>
<ol type="1">
<li>Uma primeira linha, diferente consoante se trate de um pedido (método, <em>URL</em> e versão de HTTP) ou de uma resposta (versão de HTTP, código de estado e motivo)</li>
<li>Um conjunto de cabeçalhos (<em>headers</em>), que transportam metadados sobre a mensagem (por exemplo, o anfitrião de destino, o tipo de conteúdo ou o seu comprimento)</li>
<li>Um corpo (<em>body</em>), opcional, com os dados propriamente ditos</li>
</ol>
<p>Um pedido <code>GET</code> não tem, tipicamente, corpo: todos os dados que transporta vão na própria <em>URL</em>, sob a forma de parâmetros. Um pedido <code>POST</code> transporta os dados no corpo da mensagem, fora da <em>URL</em>.</p>
<div id="fig-03-http-formato-mensagem" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-03-http-formato-mensagem-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="../assets/images/capitulos/cap03/HTTP_message_request_format.png" class="img-fluid figure-img column-body-outset" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-03-http-formato-mensagem-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.4: O formato geral de uma mensagem HTTP: a primeira linha (diferente para pedido e resposta), seguida dos vários grupos de cabeçalhos, e por fim o corpo.
</figcaption>
</figure>
</div>
<section id="exemplo-do-formulário-de-consulta-de-capital-a-um-pedido-http" class="level4">
<h4 class="anchored" data-anchor-id="exemplo-do-formulário-de-consulta-de-capital-a-um-pedido-http">Exemplo: do Formulário de Consulta de Capital a um Pedido HTTP</h4>
<p>Recorde-se o formulário de consulta de capital construído no <a href="../capitulos/cap02.html">Capítulo 2</a> (<code>capital.html</code>):</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode numberSource html number-lines code-with-copy"><code class="sourceCode html"><span id="cb3-1"><a href="#cb3-1"></a><span class="dt">&lt;</span><span class="kw">form</span><span class="ot"> method</span><span class="op">=</span><span class="st">"GET"</span><span class="ot"> action</span><span class="op">=</span><span class="st">"/capital"</span><span class="dt">&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2"></a>  <span class="dt">&lt;</span><span class="kw">label</span><span class="ot"> for</span><span class="op">=</span><span class="st">"countrycode"</span><span class="dt">&gt;</span>Código do país<span class="dt">&lt;/</span><span class="kw">label</span><span class="dt">&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3"></a>  <span class="dt">&lt;</span><span class="kw">input</span><span class="ot"> type</span><span class="op">=</span><span class="st">"text"</span><span class="ot"> id</span><span class="op">=</span><span class="st">"countrycode"</span><span class="ot"> name</span><span class="op">=</span><span class="st">"countrycode"</span><span class="dt">&gt;</span></span>
<span id="cb3-4"><a href="#cb3-4"></a>  <span class="dt">&lt;</span><span class="kw">button</span><span class="ot"> type</span><span class="op">=</span><span class="st">"submit"</span><span class="dt">&gt;</span>Consultar<span class="dt">&lt;/</span><span class="kw">button</span><span class="dt">&gt;</span></span>
<span id="cb3-5"><a href="#cb3-5"></a><span class="dt">&lt;/</span><span class="kw">form</span><span class="dt">&gt;</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Este código <code>HTML</code>renderiza no <em>browser</em> como mostrado na figura <a href="#fig-03-form-capital" class="quarto-xref">Figura&nbsp;<span>3.5</span></a>:</p>
<div id="fig-03-form-capital" class="browser-shot quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-03-form-capital-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/images/capitulos/cap03/form1.png" class="browser-shot img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-03-form-capital-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.5: O formulário de consulta de capital (<code>capital.html</code>), tal como é apresentado no <em>browser</em>.
</figcaption>
</figure>
</div>
<p>Ao ser submetido (clicando no botáo <em>Consultar</em>) com o valor <code>PT</code> no <code>input</code>, o <em>browser</em> gera a seguinte mensagem <code>GET</code> de pedido HTTP:</p>
<div class="httpmsg">
<p>GET /capital?countrycode=PT HTTP/1.1<br>
Host: localhost:8080</p>
</div>
<p>Note-se que, por se tratar de um método <code>GET</code>, o parâmetro <code>countrycode</code> é enviado como parte da <em>URL</em> (depois do <code>?</code>), e não existe corpo na mensagem. Se o mesmo formulário usasse <code>method="POST"</code>, o parâmetro seguiria antes no corpo do pedido, e a <em>URL</em> manter-se-ia limpa (<code>/capital</code>).</p>
<p>O servidor, ao processar este pedido, devolve uma resposta HTTP como a seguinte:</p>
<div class="httpmsg">
<p>HTTP/1.1 200 OK<br>
Content-Type: application/json</p>
<p>{"country": "Portugal", "capital": "Lisboa", "ccode": "PT"}</p>
</div>
</section>
<section id="exemplo-do-formulário-de-autenticação-a-um-pedido-post-com-corpo" class="level4">
<h4 class="anchored" data-anchor-id="exemplo-do-formulário-de-autenticação-a-um-pedido-post-com-corpo">Exemplo: do Formulário de Autenticação a um Pedido <code>POST</code> com Corpo</h4>
<p>Recorde-se agora o formulário de autenticação, também do <a href="../capitulos/cap02.html">Capítulo 2</a> (<code>login.html</code>), com os campos <code>user</code> e <code>pass</code>:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode numberSource html number-lines code-with-copy"><code class="sourceCode html"><span id="cb4-1"><a href="#cb4-1"></a><span class="dt">&lt;</span><span class="kw">form</span><span class="ot"> method</span><span class="op">=</span><span class="st">"POST"</span><span class="ot"> action</span><span class="op">=</span><span class="st">"/login"</span><span class="dt">&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2"></a>  <span class="dt">&lt;</span><span class="kw">label</span><span class="ot"> for</span><span class="op">=</span><span class="st">"user"</span><span class="dt">&gt;</span>Utilizador<span class="dt">&lt;/</span><span class="kw">label</span><span class="dt">&gt;</span></span>
<span id="cb4-3"><a href="#cb4-3"></a>  <span class="dt">&lt;</span><span class="kw">input</span><span class="ot"> type</span><span class="op">=</span><span class="st">"text"</span><span class="ot"> id</span><span class="op">=</span><span class="st">"user"</span><span class="ot"> name</span><span class="op">=</span><span class="st">"user"</span><span class="dt">&gt;</span></span>
<span id="cb4-4"><a href="#cb4-4"></a>  <span class="dt">&lt;</span><span class="kw">label</span><span class="ot"> for</span><span class="op">=</span><span class="st">"pass"</span><span class="dt">&gt;</span>Palavra-passe<span class="dt">&lt;/</span><span class="kw">label</span><span class="dt">&gt;</span></span>
<span id="cb4-5"><a href="#cb4-5"></a>  <span class="dt">&lt;</span><span class="kw">input</span><span class="ot"> type</span><span class="op">=</span><span class="st">"password"</span><span class="ot"> id</span><span class="op">=</span><span class="st">"pass"</span><span class="ot"> name</span><span class="op">=</span><span class="st">"pass"</span><span class="dt">&gt;</span></span>
<span id="cb4-6"><a href="#cb4-6"></a>  <span class="dt">&lt;</span><span class="kw">button</span><span class="ot"> type</span><span class="op">=</span><span class="st">"submit"</span><span class="dt">&gt;</span>Entrar<span class="dt">&lt;/</span><span class="kw">button</span><span class="dt">&gt;</span></span>
<span id="cb4-7"><a href="#cb4-7"></a><span class="dt">&lt;/</span><span class="kw">form</span><span class="dt">&gt;</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Este código <code>HTML</code>renderiza no <em>browser</em> como mostrado na figura <a href="#fig-03-form-login" class="quarto-xref">Figura&nbsp;<span>3.6</span></a>:</p>
<div id="fig-03-form-login" class="browser-shot quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-03-form-login-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/images/capitulos/cap03/form_login.png" class="browser-shot img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-03-form-login-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3.6: O formulário de autenticação (<code>login.html</code>), tal como é apresentado no <em>browser</em>.
</figcaption>
</figure>
</div>
<p>Ao ser submetido, este formulário gera o seguinte pedido HTTP:</p>
<div class="httpmsg">
<p>POST /login HTTP/1.1<br>
Host: localhost:8080<br>
Content-Type: application/x-www-form-urlencoded<br>
Content-Length: 21</p>
<p>user=javaee&amp;pass=asw2026</p>
</div>
<p>Ao contrário do exemplo anterior, os parâmetros já não vão na <em>URL</em>: seguem no corpo do pedido, depois de uma linha em branco que separa os cabeçalhos do corpo. É por isso que credenciais e outros dados sensíveis se enviam tipicamente por <code>POST</code>, nunca por <code>GET</code>: o corpo de um pedido não fica registado nos históricos de navegação nem nos ficheiros de registo (<em>logs</em>) do servidor, ao contrário do que acontece com os parâmetros de uma <em>URL</em>.</p>
<p>O servidor, ao validar as credenciais com sucesso, devolve uma resposta HTTP. Neste caso trata-se de uma aplicação orientada à apresentação (ver <a href="../capitulos/cap01.html">Capítulo 1</a>), por isso o corpo da resposta traz código HTML para o <em>browser</em> apresentar; numa aplicação orientada ao serviço, traria JSON. A resposta tem a seguinte forma:</p>
<div class="httpmsg">
<p>HTTP/1.1 200 OK<br>
Content-Type: text/html</p>
<p>&lt;h1&gt;Bem-vindo, javaee&lt;/h1&gt;<br>
&lt;p&gt;Sessão iniciada com sucesso.&lt;/p&gt;</p>
</div>
</section>
</section>
<section id="sec-03-codigos-estado" class="level3" data-number="3.7.3">
<h3 data-number="3.7.3" class="anchored" data-anchor-id="sec-03-codigos-estado"><span class="header-section-number">3.7.3</span> Códigos de Estado</h3>
<p>Toda a resposta HTTP inclui um código de estado numérico, que indica sucintamente o resultado do pedido. Os códigos agrupam-se em cinco categorias, consoante a centena:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Intervalo</th>
<th>Categoria</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>1xx</code></td>
<td>Informativo</td>
</tr>
<tr class="even">
<td><code>2xx</code></td>
<td>Sucesso</td>
</tr>
<tr class="odd">
<td><code>3xx</code></td>
<td>Redirecionamento</td>
</tr>
<tr class="even">
<td><code>4xx</code></td>
<td>Erro do cliente</td>
</tr>
<tr class="odd">
<td><code>5xx</code></td>
<td>Erro do servidor</td>
</tr>
</tbody>
</table>
<p>Dentro destas categorias, alguns códigos surgem com particular frequência no desenvolvimento de serviços Web:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Código</th>
<th>Significado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>200 OK</code></td>
<td>O pedido foi processado com sucesso</td>
</tr>
<tr class="even">
<td><code>201 Created</code></td>
<td>Um novo recurso foi criado com sucesso</td>
</tr>
<tr class="odd">
<td><code>400 Bad Request</code></td>
<td>O pedido está malformado ou falta um parâmetro obrigatório</td>
</tr>
<tr class="even">
<td><code>403 Forbidden</code></td>
<td>O cliente não tem permissão para aceder ao recurso</td>
</tr>
<tr class="odd">
<td><code>404 Not Found</code></td>
<td>O recurso pedido não existe</td>
</tr>
<tr class="even">
<td><code>500 Internal Server Error</code></td>
<td>Ocorreu um erro não tratado do lado do servidor</td>
</tr>
</tbody>
</table>
<p>Escolher o código de estado correto para cada situação é uma parte essencial do desenho de um serviço Web: o código transmite, por si só, informação que o cliente pode usar para decidir como reagir, sem precisar de interpretar o corpo da resposta.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../capitulos/cap02.html" class="pagination-link" aria-label="HTML, CSS e Bootstrap">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">HTML, CSS e Bootstrap</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../capitulos/cap04.html" class="pagination-link" aria-label="Java EE e Fundamentos de Servlets">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Java EE e Fundamentos de Servlets</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Aplicações e Serviços Web — UTAD</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>